# Generated by Django 4.0.4 on 2022-06-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C1',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=50)),
                ('curcive_text', models.CharField(max_length=50)),
                ('bold_text', models.CharField(max_length=50)),
                ('big_bold_text', models.CharField(max_length=50)),
                ('since_date', models.CharField(max_length=50)),
                ('carousal_link', models.CharField(max_length=50)),
                ('carousal_image', models.ImageField(default='', upload_to='ecomsite/images')),
            ],
        ),
    ]
