# Generated by Django 4.0.4 on 2022-06-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0002_ourstory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ourstory',
        ),
    ]
