# Generated by Django 4.0.4 on 2022-06-08 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0005_whychooseus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='whychooseus',
        ),
    ]
