# Generated by Django 4.0.4 on 2022-06-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0006_delete_whychooseus'),
    ]

    operations = [
        migrations.CreateModel(
            name='whychooseus',
            fields=[
                ('wcu_id', models.AutoField(primary_key=True, serialize=False)),
                ('wcu_title', models.CharField(max_length=100)),
                ('wcu_subtitle', models.CharField(max_length=100)),
                ('wcu_p', models.CharField(max_length=200)),
            ],
        ),
    ]
