# Generated by Django 4.0.4 on 2022-06-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0007_whychooseus'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseus',
            name='wcu_image',
            field=models.ImageField(default='', upload_to='ecomsite/images'),
        ),
    ]
