# Generated by Django 4.0.4 on 2022-06-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0008_whychooseus_wcu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='oursuppliers',
            fields=[
                ('osuppliers_id', models.AutoField(primary_key=True, serialize=False)),
                ('osuppliers_image', models.ImageField(default='', upload_to='ecomsite/images')),
            ],
        ),
    ]
