# Generated by Django 4.0.4 on 2022-06-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0010_oursuppliers_osuppliers_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeproducts',
            fields=[
                ('hp_id', models.AutoField(primary_key=True, serialize=False)),
                ('hp_title', models.CharField(default='', max_length=100)),
                ('hp_desc', models.TextField()),
                ('hp_image', models.ImageField(default='', upload_to='ecomsite/images')),
            ],
        ),
    ]
