# Generated by Django 4.0.4 on 2022-06-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0011_homeproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='homesoldproducts',
            fields=[
                ('hsp_id', models.AutoField(primary_key=True, serialize=False)),
                ('hsp_curcive_text', models.CharField(max_length=50)),
                ('hsp_title1', models.CharField(default='', max_length=100)),
                ('hsp_title2', models.CharField(default='', max_length=100)),
                ('hsp_subtitle', models.CharField(default='', max_length=100)),
                ('hsp_image', models.ImageField(default='', upload_to='ecomsite/images')),
            ],
        ),
    ]
