# Generated by Django 4.0.4 on 2022-06-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0013_weworkwith'),
    ]

    operations = [
        migrations.CreateModel(
            name='manageyoursec',
            fields=[
                ('mys_id', models.AutoField(primary_key=True, serialize=False)),
                ('mys_title', models.CharField(default='', max_length=100)),
                ('mys_image', models.ImageField(default='', upload_to='ecomsite/images')),
            ],
        ),
    ]
