# Generated by Django 4.0.4 on 2022-06-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0014_manageyoursec'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageyoursec',
            name='mys_icon1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manageyoursec',
            name='mys_icon2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manageyoursec',
            name='mys_icon3',
            field=models.CharField(default='', max_length=100),
        ),
    ]
