# Generated by Django 4.0.4 on 2022-06-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0015_manageyoursec_mys_icon1_manageyoursec_mys_icon2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageyoursec',
            name='mys_icon1',
            field=models.ImageField(default='', upload_to='ecomsite/images'),
        ),
        migrations.AlterField(
            model_name='manageyoursec',
            name='mys_icon2',
            field=models.ImageField(default='', upload_to='ecomsite/images'),
        ),
        migrations.AlterField(
            model_name='manageyoursec',
            name='mys_icon3',
            field=models.ImageField(default='', upload_to='ecomsite/images'),
        ),
    ]
