# Generated by Django 4.0.4 on 2022-06-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0016_alter_manageyoursec_mys_icon1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourfleet',
            fields=[
                ('of_id', models.AutoField(primary_key=True, serialize=False)),
                ('of_title', models.CharField(default='', max_length=100)),
                ('of_desc1', models.TextField()),
                ('of_desc2', models.TextField()),
                ('of_link', models.CharField(max_length=50)),
            ],
        ),
    ]
