# Generated by Django 4.0.4 on 2022-06-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0017_ourfleet'),
    ]

    operations = [
        migrations.CreateModel(
            name='regionsweserver',
            fields=[
                ('rws_id', models.AutoField(primary_key=True, serialize=False)),
                ('rws_title', models.CharField(default='', max_length=100)),
                ('of_p1', models.TextField()),
                ('of_p2', models.TextField()),
                ('of_link', models.CharField(max_length=50)),
            ],
        ),
    ]
