# Generated by Django 4.0.4 on 2022-06-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0018_regionsweserver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionsweserver',
            old_name='of_link',
            new_name='rws_link',
        ),
        migrations.RenameField(
            model_name='regionsweserver',
            old_name='of_p1',
            new_name='rws_p1',
        ),
        migrations.RenameField(
            model_name='regionsweserver',
            old_name='of_p2',
            new_name='rws_p2',
        ),
    ]
