# Generated by Django 4.0.4 on 2022-06-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0019_rename_of_link_regionsweserver_rws_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionsweserver',
            name='rws_image',
            field=models.ImageField(default='', upload_to='ecomsite/images'),
        ),
    ]
