# Generated by Django 4.0.4 on 2022-06-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0020_regionsweserver_rws_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(default='', max_length=100)),
                ('LastName', models.CharField(default='', max_length=100)),
                ('Phone', models.CharField(default='', max_length=100)),
                ('Password', models.CharField(default='', max_length=100)),
                ('Confirm_Password', models.CharField(default='', max_length=100)),
                ('Email', models.CharField(default='', max_length=100)),
                ('StreetAddress', models.CharField(default='', max_length=200)),
                ('City', models.CharField(default='', max_length=100)),
                ('PostalCode', models.CharField(default='', max_length=100)),
                ('Province', models.CharField(default='', max_length=100)),
                ('Country', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
