# Generated by Django 4.0.4 on 2022-06-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0021_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Confirm_Password',
            new_name='confirmpassword',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='FirstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='LastName',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='PostalCode',
            new_name='postalcode',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Province',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='StreetAddress',
            new_name='streetaddress',
        ),
    ]
