# Generated by Django 4.0.4 on 2022-06-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0022_rename_city_register_city_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='RegisterUser',
        ),
    ]
