# Generated by Django 4.0.4 on 2022-06-22 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0024_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBrand2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr_title', models.CharField(default='', max_length=100)),
                ('pr_brand', models.CharField(default='', max_length=100)),
                ('pr_supplier', models.CharField(default='', max_length=100)),
                ('pr_price', models.CharField(default='7.99', max_length=100)),
                ('pr_desc', models.TextField()),
                ('pr_detail', models.TextField(default='Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam non ummy nibh euismod tincidunt ut laoreet dolore magna aliquam eratv olu tpat. Ut wisi enim ad minim veniam lorem ipsum dolor sit amet, con sect etuer adipiscing elit, sed diam nonummy.')),
                ('flash_sale', models.BooleanField(default=False)),
                ('seasonal_sale', models.BooleanField(default=False)),
                ('show_on_home', models.BooleanField(default=False)),
                ('pr_image', models.ImageField(default='', upload_to='ecomsite/images')),
                ('pr_brn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomsite.productbrand2')),
                ('pr_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecomsite.productcategory')),
            ],
        ),

    ]
