# Generated by Django 4.0.4 on 2022-06-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0025_productbrand_productbrand2_productcategory_products_and_more'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='products',
            name='pr_brand',
        ),
    ]
