# Generated by Django 4.0.4 on 2022-06-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0028_delete_homeproducts_alter_products_pr_supplier'),
    ]

    operations = [

        migrations.AddField(
            model_name='registeruser',
            name='city1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='country1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='postalcode1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='province1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='streetaddress1',
            field=models.CharField(default='', max_length=200),
        ),
    ]
