# Generated by Django 4.0.4 on 2022-07-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomsite', '0030_cart_delete_homeproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='', max_length=100)),
                ('product_id', models.CharField(default='', max_length=100)),
                ('quantity', models.CharField(default='', max_length=100)),
            ],
        )
    ]
